spring:
  application:
    name: HmilyMerchants
  datasource:
    url: jdbc:mysql://120.79.151.179:3306/passbook?autoReconnect=true
    username: root
    password: admin
#  kafka:
#    bootstrap-servers: 127.0.0.1:9092
#    consumer:
#      group-id: passbook
#    listener:
#      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: hmily-merchants.log

